### ISSUE TITLE
[Firefox Developer Edition] Crashes with Image Preview Plugin Enabled

### ISSUE THREAD

**Issue by RRStoyanov** [pqina/jquery-filepond#6]
### Summary
When Image Preview Plugin is Enabled and a file is uploaded, Firefox Developer Edition crashes.

### How to reproduce
Go to [https://pqina.nl/filepond/#examples](https://pqina.nl/filepond/#examples) and upload a file

### Expected behaviour
Uploaded file and preview

### Additional information
N/A

| Environment  | Version
|------------- | -----------
| OS           | Windows 10
| Browser      | Firefox Developer Edition 64.0b5 (64-bit)

**Comment by rikschennink** [comment]
It does indeed, not sure why, the normal version works fine, maybe the dev version has some experimental features enabled.

**Comment by rikschennink** [comment]
Just published version `3.1.4` of the image preview plugin which fixes this issue.

Turns out, Firefox Nightly/Dev crashed when sending an object URL (`URL.createObjectURL(file)`) to a WebWorker and using `fetch(objectUrl).then(res => res.blob())` to turn it back into a `file` again.

I'm not sure why I initially set it up with object URLs as it's also possible to send File objects to WebWorkers.

Please confirm the issue is resolved.
